/*Lesson 13. Creating Advanced Joins
In this lesson, you’ll learn all about additional join types—what they are and
how to use them. You’ll also learn how to use table aliases and how to use
aggregate functions with joined tables.*/

SELECT RTRIM(vend_name) + ' (' + RTRIM(vend_country) + ')'
AS vend_title
FROM Vendors
ORDER BY vend_name;SELECT cust_name, cust_contact
FROM Customers AS C, Orders AS O, OrderItems AS OI
WHERE C.cust_id = O.cust_id
AND OI.order_num = O.order_num
AND prod_id = 'RGAN01';SELECT cust_id, cust_name, cust_contactFROM CustomersWHERE cust_name = (SELECT cust_name			       FROM Customers				   WHERE cust_contact = 'Jim Jones');SELECT c1.cust_id, c1.cust_name, c1.cust_contactFROM Customers AS c1, Customers AS c2WHERE c1.cust_name = c2.cust_nameAND c2.cust_contact = 'Jim Jones';SELECT * FROM Customers;SELECT C.*, O.order_num, O.order_date, OI.prod_id, OI.quantity, OI.item_priceFROM Customers AS C, Orders AS O, OrderItems AS OIWHERE C.cust_id = O.cust_idAND OI.order_num = O.order_numAND prod_id = 'RGAN01';SELECT Customers.cust_id, Orders.order_numFROM CustomersINNER JOIN Orders ON Customers.cust_id = Orders.cust_id;SELECT Customers.cust_id, Orders.order_numFROM CustomersLEFT OUTER JOIN Orders ON Customers.cust_id = Orders.cust_id;SELECT Customers.cust_id, Orders.order_numFROM CustomersRIGHT OUTER JOIN Orders ON Customers.cust_id = Orders.cust_id;SELECT Customers.cust_id, Orders.order_numFROM CustomersFULL OUTER JOIN Orders ON Customers.cust_id = Orders.cust_id;SELECT Customers.cust_id, COUNT(Orders.order_num) AS num_ordFROM CustomersINNER JOIN Orders ON Customers.cust_id = Orders.cust_idGROUP BY Customers.cust_id;SELECT Customers.cust_id, COUNT(Orders.order_num) AS num_ordFROM CustomersLEFT OUTER JOIN Orders ON Customers.cust_id = Orders.cust_idGROUP BY Customers.cust_id;SELECT cust_name, order_numFROM CustomersINNER JOIN Orders ON Customers.cust_id = Orders.cust_idORDER BY cust_name;  --challenge 1SELECT cust_name, order_numFROM CustomersLEFT OUTER JOIN Orders ON Customers.cust_id = Orders.cust_idORDER BY cust_name;  --challenge 2SELECT prod_name, order_numFROM ProductsLEFT OUTER JOIN OrderItems ON OrderItems.prod_id = Products.prod_idORDER BY prod_name;  --challenge 3SELECT prod_name, COUNT(order_num) AS num_ordFROM ProductsLEFT OUTER JOIN OrderItems ON OrderItems.prod_id = Products.prod_idGROUP BY prod_nameORDER BY prod_name;  --challenge 4SELECT prod_name, COUNT(order_num) AS num_ordFROM Products, OrderItemsGROUP BY prod_nameORDER BY prod_name;SELECT * FROM OrderItems;SELECT Vendors.vend_id, COUNT(prod_id) AS num_prodFROM VendorsLEFT OUTER JOIN Products ON Vendors.vend_id = Products.vend_idGROUP BY Vendors.vend_idORDER BY Vendors.vend_id;  --challenge 5